# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B -DskipTests=true -P=jcasgen,release package

    - name: Add JARs to Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'release'
      with:
        files: |
          ${{ github.workspace }}/target/typesystem-*.jar

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B -s ${{ github.workspace }}/settings.xml -DskipTests=true -P=-jcasgen,release deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
